### ISSUE TITLE
Unable to sign tx

### ISSUE THREAD

**Issue by friedger** [amorriscode/stx-me#1]
I tried to donate but the stacks wallet failed:
![Screenshot from 2021-05-21 07-00-29](https://user-images.githubusercontent.com/1449049/119084570-4e392180-ba02-11eb-9a4c-bc89b2b369f4.png)

There is no logout button or so. Any ideas what goes wrong?

I am using Stacks Wallet 2.7.1

**Comment by amorriscode** [comment]
@friedger sorry about that! Will try to look into it ASAP.

**Comment by amorriscode** [comment]
@friedger not sure what happened but transactions work now. I'm going to implement a logout function as well.
