### ISSUE TITLE
Chrome extension favicon.ico missing - causes broken image on stx webwallet

### ISSUE THREAD

**Issue by dcdigit** [amorriscode/stx-me#3]
It looks like you need a favicon.ico file to send to the stx webwallet.
Here is what it looks like when I attempt to send you stx:
<img width="554" alt="Screen Shot 2021-07-31 at 3 04 29 PM" src="https://user-images.githubusercontent.com/47461971/127750189-70dab1d0-3466-47e8-be4d-918a4cbedbe9.png">

**Comment by amorriscode** [comment]
Good call, thanks @dcdigit!
